name: Test Build

on:

  push:
    branches: [ master ]

  pull_request:
    branches: [ master ]

jobs:

  linux-build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    
    - name: NPM Install
      run: |
        npm install -g electron-packager
        npm install -g @angular/cli
        npm install -g ngx-i18nsupport
        npm install

    - name: Build Linux
      run: npm run electron:linux


  windows-build:

    runs-on: windows-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: NPM Install
      run: |
        npm install -g electron-packager
        npm install -g @angular/cli
        npm install -g ngx-i18nsupport
        npm install

    - run: npm run electron:windows

